import React,{useState} from 'https://esm.sh/react@19';
import{createRoot}from'https://esm.sh/react-dom@19/client';
import{ArrowUpRight,Download,Menu,X,Linkedin,Dribbble,Mail,MapPin}from'https://esm.sh/lucide-react@0.468.0';
import'./style.css';

const projects=[
 ['Finwise','Mobile banking made reassuringly simple.','Fintech · Product design','https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1400&q=85'],
 ['Metric OS','Turning complex analytics into clear decisions.','SaaS · Design system','https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85'],
 ['Grounded','A calmer way to build healthier habits.','Wellness · Mobile app','https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=85'],
 ['Loop Learning','Making remote learning feel more human.','Edtech · Web platform','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85']
];
const skills=['UX strategy','User research','Product design','Design systems','Prototyping','Usability testing'];
function App(){
 const[open,setOpen]=useState(false);const[modal,setModal]=useState(null);const[sent,setSent]=useState(false);
 return <><header><a className="logo" href="#">JD<span>.</span></a><nav className={open?'open':''}>{['Work','About','Experience','Contact'].map(x=><a onClick={()=>setOpen(false)} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><a className="avail" href="#contact"><i/>Available for new projects</a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
 <main>
 <section className="hero" id="about"><div className="eyebrow">Hello, I’m Jordan · UX designer</div><h1>I turn complexity into <em>clear, useful</em> experiences.</h1><div className="hero-grid"><div className="portrait"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1200&q=90"/><span>Product thinking</span><span>Human-centered</span></div><div className="intro"><p>I design digital products that balance user needs, business goals, and technical reality. My work turns ambiguity into experiences people understand and enjoy.</p><div className="actions"><a className="primary" href="#work">View selected work <ArrowUpRight/></a><a className="secondary" href="#experience"><Download/> Download résumé</a></div><div className="meta"><div><Mail/> jordan@design.com</div><div><MapPin/> Chicago, IL</div></div></div></div></section>
 <section className="skills"><div className="eyebrow">What I do</div><div className="section-head"><h2>Design solutions that make an impact.</h2><p>From early discovery to polished interfaces, I help teams make confident product decisions.</p></div><div className="skill-grid">{skills.map((s,i)=><article><b>0{i+1}</b><h3>{s}</h3><ArrowUpRight/></article>)}</div></section>
 <section className="experience" id="experience"><div><div className="eyebrow">About me</div><h2>Designing with purpose, curiosity, and clarity.</h2><p>I’ve spent the last seven years helping startups and product teams shape ideas into thoughtful, measurable experiences.</p><a className="primary" href="#contact">Let’s work together <ArrowUpRight/></a></div><div className="timeline">{[['2023—Now','Lead Product Designer','Northstar Labs'],['2020—2023','Senior UX Designer','Common Thread'],['2018—2020','Product Designer','Brightworks Studio']].map(x=><article><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
 <section className="work" id="work"><div className="eyebrow">Selected projects</div><div className="section-head"><h2>Work built around real people.</h2><p>Four snapshots of how I approach complex product challenges.</p></div><div className="projects">{projects.map((p,i)=><article onClick={()=>setModal(i)}><div className="project-img"><img src={p[3]}/><button aria-label={'Open '+p[0]}><ArrowUpRight/></button></div><p>{p[2]}</p><h3>{p[0]}</h3><h4>{p[1]}</h4></article>)}</div></section>
 <section className="quote"><p>“Jordan brings structure to messy problems and keeps the entire team focused on what matters most: the person using the product.”</p><span>Maya Chen · VP Product, Northstar</span></section>
 <section className="contact" id="contact"><div><div className="eyebrow">Let’s talk</div><h2>Have a problem worth solving?</h2><p>Tell me what you’re building, what’s getting in the way, and where you’d like to go next.</p><div className="social"><a><Linkedin/></a><a><Dribbble/></a><a><Mail/></a></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Project type<select><option>Product design</option><option>UX research</option><option>Design system</option></select></label><label>Message<textarea required placeholder="A little about your project..."/></label><button className="primary">{sent?'Message sent — thank you':'Send message'} <ArrowUpRight/></button></form></section>
 </main><footer><a className="logo">JD<span>.</span></a><p>UX designer creating useful, lasting digital experiences.</p><span>© 2026 Jordan Design</span></footer>
 {modal!==null&&<div className="modal" onClick={()=>setModal(null)}><div onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button><img src={projects[modal][3]}/><div className="eyebrow">{projects[modal][2]}</div><h2>{projects[modal][0]}</h2><p>{projects[modal][1]} This case study covers discovery, synthesis, prototyping, and the design decisions that moved the product forward.</p><button className="primary" onClick={()=>setModal(null)}>Close case study</button></div></div>}
 </>}
createRoot(document.getElementById('root')).render(<App/>);
