import React,{useState} from 'react';
import {ArrowUpRight,ArrowLeft} from 'lucide-react';
import {Button} from '@/components/ui/button';
import showcase from './forma-showcase.json';
const figmaUrl='https://www.figma.com/design/x1XvrxK8bBpZaCzpvfj2da/Casting-Studio-Dashboard-UI-Kit';
export default function FormaShowcase({p,Figure,Gate,Footer}){
 const [unlocked,setUnlocked]=useState(()=>{try{return sessionStorage.getItem('daniel-projects-unlocked')==='true'}catch{return false}});
 return <><main id="main" className="forma-showcase"><section className="case-hero"><a className="back-link" href="./#work"><ArrowLeft size={16}/>All work</a><p className="eyebrow">{p.category}</p><h1>FORMA</h1><p className="case-subtitle">{p.intro}</p><div className="prototype-action"><Button asChild size="lg"><a href={figmaUrl} target="_blank" rel="noreferrer">Explore the Figma file<ArrowUpRight size={18}/></a></Button><span>Foundations → Components → Complete experiences</span></div><div className="case-meta"><div><span>Scope</span><p>Design system & product experience</p></div><div><span>Coverage</span><p>Studio workflows, public website, desktop & mobile</p></div><div><span>Design tool</span><p>Figma</p></div></div></section>{!unlocked?<Gate onUnlock={()=>setUnlocked(true)}/>:<><Figure file={p.image} caption={p.alt} hero/><div className="forma-facts"><div><strong>29</strong><span>Documented semantic colors</span></div><div><strong>Manrope</strong><span>Studio UI + editorial type scales</span></div><div><strong>28</strong><span>Original Figma exports</span></div><div><strong>2</strong><span>Desktop & mobile design contexts</span></div></div><div className="case-layout"><aside><nav aria-label="Design system sections"><p className="eyebrow">Explore the system</p>{showcase.sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.label}</a>)}</nav></aside><div className="case-body">{showcase.sections.map((s,i)=><section id={s.id} key={s.id}><p className="eyebrow">{String(i+1).padStart(2,'0')} / {s.label}</p><h2>{s.title}</h2>{s.paragraphs.map(t=><p className="forma-paragraph" key={t}>{t}</p>)}{s.id==='color'&&<div className="forma-swatches">{[['Stage','#08090A'],['Surface','#1C1D20'],['Text','#F4F4F2'],['Accent','#FF8A4C'],['Cream','#F8F4EE'],['Success','#B8D6A2']].map(([name,color])=><div key={name}><span style={{background:color}}/><strong>{name}</strong><code>{color}</code></div>)}</div>}<div className={`forma-gallery forma-gallery-${s.id}`}>{s.images.map(([file,caption])=><Figure file={file} caption={caption} key={file}/>)}</div>{s.id==='next'&&<a className="text-link" href={figmaUrl} target="_blank" rel="noreferrer">Explore all screens in Figma<ArrowUpRight size={16}/></a>}</section>)}</div></div></>}<a className="next-project" href="./enta.html"><div><p className="eyebrow">Next case study</p><h2>Enta</h2></div><ArrowUpRight/></a></main><Footer/></>;
}
