export default {
  'meridian': {lead:'I led the experience design for Meridian, translating a payments API into a connected developer journey that moves from evaluation to first call, recovery, event delivery, and production readiness.',actions:['Mapped the developer journey, audience needs, platform risks, and moments where context is commonly lost.','Designed the workspace architecture, documentation model, API explorer, scoped access, error recovery, logs, webhooks, and readiness review.','Built and evaluated the interactive concept across first-call success, permission failure, validation recovery, delivery retry, and theme states.']},
  'dev-mode': {lead:'I led the experience design for API Launchpad, defining the journey from API evaluation to production readiness and translating technical platform requirements into a workspace developers can understand and act on.',actions:['Mapped the end-to-end developer journey and its failure points.','Designed the information architecture, onboarding, API explorer, recovery patterns, logs, and readiness checklist.','Built and evaluated the interactive prototype across successful calls, permission failures, validation errors, and webhook retries.']},
  'forma': {lead:'I designed the product experience and the design system that supports it, connecting foundational decisions to complete casting workflows across desktop, mobile, and the public website.',actions:['Defined the color, typography, spacing, surface, and responsive foundations.','Designed reusable components for actions, forms, navigation, records, media, and dialogs.','Applied the system to casting creation, availability, booking, shortlisting, talent profiles, and client review.']},
  'enta': {lead:'As lead designer, I shaped how customers understand and move between cross-border money, bank destinations, wallets, and digital assets without exposing the complexity of the underlying routes.',actions:['Structured the product around customer intent and destination type.','Designed the send, receive, purchase, balance, and transaction-state experiences.','Established the information hierarchy for amounts, fees, conversion, access, and next actions.']},
  'metric-os': {lead:'I led the product-design direction for an observability workspace that helps teams move from a system signal to a defensible operational decision.',actions:['Synthesized the incident journey across topology, telemetry, evidence, and response.','Designed the investigation hierarchy and interaction model for correlated system context.','Prototyped how recommendations, confidence, and rollback decisions could remain inspectable.']},
  'sendory': {lead:'I designed Sendory as an innovation concept for composing polished newsletters from reusable content blocks, templates, and contextual controls.',actions:['Defined the composition workflow from template selection to final review.','Designed the component palette, live canvas, properties panel, and editing states.','Built the interactive prototype to test whether structure and creative control could coexist.']},
  'flownode': {lead:'I designed the workflow-building experience, turning an automation idea into a sequence people can inspect, configure, and approve before execution.',actions:['Mapped the workflow from natural-language intent to connected operational steps.','Designed branching, validation, human approval, and status patterns.','Built an interactive prototype to make the automation model tangible and reviewable.']},
  'agent-os': {lead:'I designed how Agent OS explains its value, capabilities, and operating model to people evaluating an unfamiliar AI platform.',actions:['Restructured the information architecture around evaluation questions.','Designed the product story, capability hierarchy, proof points, and calls to action.','Created a responsive web experience that balances technical credibility with approachable language.']},
  'iretv': {lead:'I created IreTV from product strategy through interface design, shaping how viewers discover, evaluate, access, and return to faith-centered entertainment.',actions:['Defined the product proposition and the discovery-to-viewing journey.','Designed the content hierarchy, title evaluation, access, library, and return-viewing patterns.','Built the interface and documented the next validation and launch decisions.']},
  'finwise': {lead:'I designed ArtoQu to make everyday financial information easier to scan, compare, and act on across a dense dashboard experience.',actions:['Prioritized balances, spending, savings, and recent activity around common financial questions.','Designed the dashboard hierarchy, navigation, transfer, and savings interactions.','Built the prototype to test clarity across summary and detail states.']},
  'pulse': {lead:'I designed the settlement-operations experience, focusing on how teams trace money movement, investigate exceptions, and understand partner activity.',actions:['Mapped the path from quote and transaction through settlement and reconciliation.','Designed operational dashboards, status language, exception handling, and partner context.','Connected high-level performance signals to the records needed for investigation.']},
  'arca': {lead:'I designed the mobile wallet experience around the financial questions people need to answer quickly: what they have, what changed, and what they can do next.',actions:['Defined the mobile information hierarchy for balances, budgets, activity, and cards.','Designed primary money actions and the transitions between overview and detail.','Built the interactive prototype to evaluate navigation and financial clarity.']},
  'shiftsnap': {lead:'I designed the mobile workforce experience to help hourly employees understand schedules, handle changes, and act without unnecessary coordination.',actions:['Mapped the core scheduling and shift-management journey.','Designed the mobile hierarchy for upcoming work, availability, changes, and confirmations.','Connected status, time, location, and action cues so each shift remains understandable.']},
  'interoly': {lead:'I designed the inventory-management experience around work happening close to the shelf, order, and stock movement.',actions:['Structured the information architecture around inventory and order tasks.','Designed mobile workflows for finding items, understanding stock state, and taking action.','Built the prototype to connect overview metrics with operational records.']},
  'shoppulse': {lead:'I designed ShopPulse to connect store-performance signals with the products and orders that explain them.',actions:['Defined the analytical journey from dashboard signal to operational detail.','Designed the information architecture for revenue, products, orders, and inventory context.','Built the responsive prototype to test scanability and investigation flow.']},
  'urbandrive': {lead:'I designed the vehicle-rental journey from discovery to booking, helping customers compare the details that shape suitability, confidence, and total cost.',actions:['Mapped the search, comparison, vehicle-detail, and booking journey.','Designed filters and content hierarchy around trip needs and vehicle attributes.','Clarified price, availability, requirements, and the next commitment at each stage.']},
  'solshine': {lead:'I designed the complete Solshine website template, creating a reusable page system for service discovery, company credibility, and enquiries.',actions:['Defined the visual direction, page hierarchy, and responsive content structure.','Designed repeatable service, company, proof, and contact sections.','Connected the homepage, service pages, supporting information, and enquiry path into one template system.']}
};
